M48
; DRILL file {KiCad 7.0.11+dfsg-1build4} date mié 15 oct 2025 20:37:04
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-10-15T20:37:04-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11+dfsg-1build4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.500
%
G90
G05
T1
X104.5Y-53.0
X104.5Y-117.0
X157.5Y-85.0
X210.5Y-53.0
X210.5Y-117.0
M30
