M48
; DRILL file {KiCad 7.0.11+dfsg-1build4} date lun 24 nov 2025 12:58:36
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-24T12:58:36-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11+dfsg-1build4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
%
G90
G05
T1
X105.5Y-124.5
X112.5Y-144.5
X162.5Y-104.5
X162.5Y-144.5
X169.5Y-124.5
M30
